### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by rickerd** [morris/microdb#12]
I'm not able to make a new tag @morris

**Comment by morris** [comment]
Which version should the release be? v0.2.0? Also are you sure you want to ship with #8 still open?

**Comment by morris** [comment]
BTW the README currently says microdb works with PHP 5.3+ but I believe you've made additions which are incompatible. Would you mind updating README, Composer and Travis files to reflect your changes? For Travis, you'd want to add the minimum PHP version to test (e.g. 5.4).

**Comment by rickerd** [comment]
True... should it rather be 0.1.1?
The subtree thing is merged now ofcourse.

And i havent had time to dive into #8
Do you have any idea or time?

**Comment by morris** [comment]
I currently don't use microdb, so unfortunately it might take some time until I really look at things again. Sorry :(

**Comment by rickerd** [comment]
Okay we're good to go.
- Added badges for
  -- builds
  -- coverage
  -- version
  -- repo size

Also i've set the minimal version of php 5.4 and test in travis on php 7.
I've set composer to v0.1.1

If i can do anything more, let me know

**Comment by morris** [comment]
I've just released 0.1.1, not really happy with shipping bugs though :O but since I'm not using it i shouldn't be complaining... in any case, thanks for your effort!! Will further help with releases and such if you need assistance.

**Comment by rickerd** [comment]
Ill try to remove the bug but im not actively with time at the moment.
I know, i don't like bugs too.
