### ISSUE TITLE
Best way to find MicroDB id?

### ISSUE THREAD

**Issue by dejan7** [morris/microdb#13]
Hello, loving the package, i'm using it as a main DB for a small hobby project. 

I'm building an API and let's say i want to have an endpoint where i update data about a certain user for a given username.

However, updating the user is tricky because `$db->save` expects first parameter to be MicroDB id.  My first idea is to run `eachId` method and find which user has the given username and then return found user's MicroDB id and use it to `save`.

This seems kinda clunky, is there a better approach to this?

**Comment by morris** [comment]
To be completely honest, I'm not really maintaining MicroDB anymore because SQLite is almost always a better choice, widely available and easy to setup.

Concerning your use case, you'd probably use an index on usernames, but then again see #8. Sorry!
