### ISSUE TITLE
Add first tag

### ISSUE THREAD

**Issue by rickerd** [morris/microdb#5]
Having a tag makes it better to checkout using composer

**Comment by morris** [comment]
Since I'm not actively working on this, I've just added you as a collaborator. Go ahead and fix things as you see fit :beers:

**Comment by rickerd** [comment]
So funny, was looking at your repo today.
Im going to work with it again so maby i see some things.

Thanks for the rights and trust 🍻

**Comment by rickerd** [comment]
I've added the first tag.
Could you check and accept?

https://github.com/morris/microdb/pull/7

**Comment by morris** [comment]
https://help.github.com/articles/permission-levels-for-a-user-account-repository/ looks like you should be able to merge it next time :)

**Comment by rickerd** [comment]
I like to have you review the PR because my name was in it.
The company where i work has the system to always have your code checked out by another developer.

So for this first one, it was you. Next time ill merge and push it myself.

Thanks! :+1:
